// Generated by CoffeeScript 1.6.3
(function() {
  var App;

  requirejs.config({
    baseUrl: 'libs',
    paths: {
      main: '../main'
    }
  });

  App = new Marionette.Application;

  require(['main'], function(Main) {
    return Main();
  });

}).call(this);
