// Generated by CoffeeScript 1.6.3
(function() {
  requirejs.config({
    baseUrl: 'libs',
    paths: {
      main: '../main'
    }
  }, window.App = new Marionette.Application);

  require(['main'], function(Main) {
    return Main();
  });

}).call(this);
