// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define([], function() {
    var Word, Words, _ref, _ref1;
    Word = (function(_super) {
      __extends(Word, _super);

      function Word() {
        _ref = Word.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Word.prototype.idAttribute = '_id';

      return Word;

    })(Backbone.Model);
    Words = (function(_super) {
      __extends(Words, _super);

      function Words() {
        _ref1 = Words.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      Words.prototype.model = Word;

      return Words;

    })(Backbone.Collection);
    return {
      model: Word,
      collection: Words
    };
  });

}).call(this);
